# read in the Gauss-Hermite quadrature rule
# that was generated by an external program
# see John Burkardt (FSU, LGPL-code)


library(dplyr)


read.delim("data-raw/hoAll_xw.txt") %>%
  dplyr::arrange_(~order) ->

  ghQuadRule

devtools::use_data(ghQuadRule, internal = TRUE, overwrite = TRUE)

